<a href="https://colab.research.google.com/github/Kushagra651/NLP/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
from tensorflow.keras.preprocessing.text import one_hot

In [65]:
pip install tensorflow

In [66]:
sent = ['the glass of mik',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of word',
        'your videos are good',]

In [67]:
import tensorflow as tf

In [68]:
# one hot encoding

In [69]:
sent

['the glass of mik',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of word',
 'your videos are good']

In [70]:
voc_size = 500

In [71]:
onehot = [one_hot(words,voc_size) for words in sent]
print(onehot)

[[428, 140, 256, 428], [428, 140, 256, 34], [428, 192, 256, 493], [332, 120, 118, 70, 146], [332, 120, 118, 70, 245], [41, 428, 61, 256, 404], [25, 450, 349, 70]]


In [72]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [73]:
import numpy as np

In [74]:
sent_length = 8
embedded_docs = pad_sequences(onehot,maxlen = sent_length,padding='pre')
print(embedded_docs)

[[  0   0   0   0 428 140 256 428]
 [  0   0   0   0 428 140 256  34]
 [  0   0   0   0 428 192 256 493]
 [  0   0   0 332 120 118  70 146]
 [  0   0   0 332 120 118  70 245]
 [  0   0   0  41 428  61 256 404]
 [  0   0   0   0  25 450 349  70]]


In [75]:
dim =10

In [76]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [77]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [78]:

print(model.predict(embedded_docs[1]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step
[[-0.00932271  0.02808303  0.03203951 -0.0067041  -0.04126082  0.04736023
   0.02090654  0.04043218  0.00722569 -0.04035635]
 [-0.00932271  0.02808303  0.03203951 -0.0067041  -0.04126082  0.04736023
   0.02090654  0.04043218  0.00722569 -0.04035635]
 [-0.00932271  0.02808303  0.03203951 -0.0067041  -0.04126082  0.04736023
   0.02090654  0.04043218  0.00722569 -0.04035635]
 [-0.00932271  0.02808303  0.03203951 -0.0067041  -0.04126082  0.04736023
   0.02090654  0.04043218  0.00722569 -0.04035635]
 [ 0.03344202 -0.00117433  0.0372659  -0.00698825 -0.03336862  0.04078064
  -0.02765366  0.02898213 -0.03694909  0.0180355 ]
 [-0.02803017 -0.0339658   0.04469249 -0.03500452 -0.02022357 -0.01933842
   0.00590724  0.00637314  0.04263773  0.02225522]
 [ 0.04951492 -0.01411804 -0.03658029  0.04317761 -0.01653569  0.02907431
  -0.02192886  0.01161479 -0.04861437 -0.0227138 ]
 [ 0.03330464  0.04692436 -0.04603034 -0.03840669 -0.00174982 -0.01571537
   0.0333763

In [79]:
newsent = ["this is the best anime of all time"
           "and the name of thiss anime is "
           "one piece and the best new gen anime"
           "is jujutsu kaisen and "
           "my fav character is Satoru gojo who is the honoured one"
           "throughout heaven and earth i alone am the honoured one"]

In [80]:
vocabulary_size = 5000

In [81]:
onehot = [one_hot(words,vocabulary_size) for words in newsent]

In [82]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [83]:
sent_length = 10

In [89]:
embedded_docr = pad_sequences(onehot,maxlen = sent_length,padding='pre')
print(embedded_docr)

[[4479 3056 2140 3395 4990 1126 1790  919 3665 2638]]


In [90]:
dimension  =10

In [91]:
model = Sequential()
model.add(Embedding(vocabulary_size,dimension,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [92]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [93]:
model.predict(embedded_docr)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step


array([[[ 0.01752055,  0.02668381, -0.02840817, -0.00147296,
         -0.01974765,  0.01762767, -0.04159464,  0.00227047,
          0.01783231,  0.02448776],
        [ 0.04135877, -0.03240049,  0.00428564, -0.01601862,
         -0.01907623, -0.0113375 ,  0.00958297,  0.04684469,
         -0.04122066, -0.00604244],
        [-0.02064893,  0.01506775,  0.01471082,  0.00668508,
         -0.02365345, -0.03252456, -0.03450066,  0.02035398,
          0.04596275, -0.04833033],
        [-0.02787035,  0.04857024, -0.04219336, -0.00308418,
         -0.02400919,  0.02304448, -0.02619644, -0.0080214 ,
         -0.04672223, -0.03980254],
        [-0.04366831, -0.01780985,  0.03803246,  0.03035859,
          0.0112981 , -0.03588269,  0.04674235, -0.01680265,
          0.03735116,  0.02679881],
        [ 0.01826039, -0.02343434, -0.04305234, -0.02295649,
          0.01436179,  0.03318259,  0.00440962, -0.04686968,
          0.02008383, -0.02765266],
        [ 0.0112351 , -0.02507839, -0.01834039, -0.0